server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://usuario-service
          predicates:
            - Path=/usuario/**
        - id: car-service
          uri: lb://car-service
          predicates:
            - Path=/car/**
        - id: moto-service
          uri: lb://moto-service
          predicates:
            - Path=/moto/**
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost
