server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5433/springServices
    username: postgres
    password: masterkey
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    fetch-registry: true
    register-witch-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}